import axios from 'axios';

const r = arr => arr[Math.floor(Math.random() * arr.length)];
const rand = (a, b) => Math.floor(Math.random() * (b - a + 1)) + a;

const BREAKUP_LINES = [
  "We need to talk... this isn't working anymore.",
  "I've been thinking, and I think we should go our separate ways.",
  "It's not you, it's me. Actually, it might be you a little.",
  "I love you, but I'm not IN love with you anymore.",
  "I think we've grown apart and it's time to move on.",
  "You deserve someone who can give you what I can't.",
  "I'm sorry, but my feelings have changed.",
  "I think we rushed into this. Let's take some time apart.",
  "I value our friendship but I don't think we're meant to be together.",
  "This is one of the hardest things I've ever had to say... goodbye.",
  "I can't keep pretending everything is okay between us.",
  "We want different things in life and that's okay, but we can't be together.",
  "The connection we once had just isn't there anymore.",
  "I'll always care about you, but I can't be with you.",
  "I need space to figure out who I am outside of this relationship."
];

const RIZZ_LINES = [
  "Are you a parking ticket? Because you've got 'fine' written all over you.",
  "Do you have a name, or can I call you mine?",
  "Are you a magician? Because whenever I look at you, everyone else disappears.",
  "Is your name Google? Because you have everything I've been searching for.",
  "Do you believe in love at first sight, or should I walk past again?",
  "Are you a keyboard? Because you're just my type.",
  "If you were a vegetable, you'd be a 'cute-cumber'.",
  "Do you have a map? I keep getting lost in your eyes.",
  "Are you a campfire? You're hot and I want s'more.",
  "I must be a snowflake, because I've fallen for you.",
  "Are you Wi-Fi? Because I'm feeling a connection.",
  "Do you like science? Because we have great chemistry.",
  "Are you a bank loan? Because you have my interest.",
  "If beauty were time, you'd be an eternity.",
  "I'd say 'God bless you' but it looks like He already did."
];

const CHOOSE_OPTIONS = ['Option A', 'Option B', 'Rock', 'Paper', 'Scissors', 'Left', 'Right', 'Yes', 'No', 'Maybe'];

const EXCUSE_LIST = [
  "My dog ate my homework... and my phone... and my motivation.",
  "I was abducted by aliens and they only returned me 5 minutes ago.",
  "My WiFi was down and I couldn't function.",
  "I was helping an old lady cross the street — for 3 hours.",
  "I got lost in a YouTube rabbit hole about medieval bread.",
  "My horoscope said it wasn't a good day for responsibilities.",
  "I accidentally set my alarm for PM instead of AM.",
  "My plant was looking sad and I had to comfort it.",
  "I was in a deep philosophical debate with my reflection.",
  "My phone died and I forgot I existed without it.",
  "I was stress-eating and couldn't stop until the whole bag was gone.",
  "A cat sat on my laptop and deleted my work.",
  "I was doing research for 'future me' to solve.",
  "I sneezed and somehow that took 4 hours.",
  "I was mentally preparing to start and lost track of time."
];

const IQ_COMMENTS = {
  low: ['You might want to retake that...', 'Ouch.', 'At least you tried!', 'Don\'t worry, emotional intelligence matters too.'],
  mid: ['Average Joe!', 'Pretty solid!', 'Not bad at all.', 'You\'re doing okay!'],
  high: ['Big brain time!', 'Impressive!', 'Galaxy brain detected!', 'You\'re no ordinary person!']
};

function generateShipScore(name1, name2) {
  let score = 0;
  for (let i = 0; i < name1.length; i++) score += name1.charCodeAt(i);
  for (let i = 0; i < name2.length; i++) score += name2.charCodeAt(i);
  return ((score % 41) + 60); // 60-100 for fun
}

export default [
  {
    command: 'breakup',
    aliases: ['dumped', 'goodbye-msg'],
    category: 'fun',
    description: 'Generate a breakup message',
    usage: '.breakup',
    async handler(sock, message, args, context) {
      const { chatId } = context;
      const line = r(BREAKUP_LINES);
      await sock.sendMessage(chatId, {
        text: `💔 *Breakup Message*\n\n"${line}"\n\n_Generated by EDWARD MD_`
      }, { quoted: message });
    }
  },
  {
    command: 'rizz',
    aliases: ['pickup', 'flirtline', 'rizzup'],
    category: 'fun',
    description: 'Generate a rizz / pickup line',
    usage: '.rizz',
    async handler(sock, message, args, context) {
      const { chatId } = context;
      const line = r(RIZZ_LINES);
      await sock.sendMessage(chatId, {
        text: `😏 *Rizz Line*\n\n"${line}"\n\n_Use responsibly 😂_`
      }, { quoted: message });
    }
  },
  {
    command: 'ship',
    aliases: ['shiplove', 'couple-score'],
    category: 'fun',
    description: 'Check compatibility between two people',
    usage: '.ship <name1> and <name2>',
    async handler(sock, message, args, context) {
      const { chatId } = context;
      const text = args.join(' ');
      const parts = text.split(/\band\b/i);
      if (parts.length < 2) {
        return sock.sendMessage(chatId, { text: '💑 Usage: `.ship <name1> and <name2>`\n\nExample: `.ship John and Jane`' }, { quoted: message });
      }
      const name1 = parts[0].trim();
      const name2 = parts[1].trim();
      if (!name1 || !name2) {
        return sock.sendMessage(chatId, { text: '❌ Please provide two names! Example: `.ship John and Jane`' }, { quoted: message });
      }
      const score = generateShipScore(name1.toLowerCase(), name2.toLowerCase());
      const bar = '❤️'.repeat(Math.round(score / 10)) + '🖤'.repeat(10 - Math.round(score / 10));
      const comment = score >= 85 ? '💍 Perfect match! You were made for each other!' :
                      score >= 70 ? '💕 Great compatibility! Things look promising!' :
                      score >= 55 ? '😊 Pretty good! Give it a shot!' :
                      '😅 It\'s complicated, but love always finds a way!';
      await sock.sendMessage(chatId, {
        text: `💑 *Ship Score*\n\n${name1} ❤️ ${name2}\n\n${bar}\n\n💯 Compatibility: *${score}%*\n\n${comment}`
      }, { quoted: message });
    }
  },
  {
    command: 'birthday',
    aliases: ['bday', 'happybirthday', 'hbd'],
    category: 'fun',
    description: 'Send a birthday wish',
    usage: '.birthday <name>',
    async handler(sock, message, args, context) {
      const { chatId } = context;
      const name = args.join(' ').trim() || 'You';
      const wishes = [
        `May all your dreams come true!`,
        `Wishing you all the happiness life can hold!`,
        `May this year bring you amazing adventures!`,
        `Here's to another year of awesomeness!`,
        `May your day be as wonderful as you are!`
      ];
      const wish = r(wishes);
      await sock.sendMessage(chatId, {
        text: `🎂 *Happy Birthday, ${name}!* 🎉\n\n🎈🎊🥳🎁🎂\n\n${wish}\n\n🕯️ Many more years of joy ahead!\n\n_— EDWARD MD Wishes You Well_ 🤖`
      }, { quoted: message });
    }
  },
  {
    command: 'choose',
    aliases: ['pick', 'decide', 'or'],
    category: 'fun',
    description: 'Help you choose between options',
    usage: '.choose <option1> or <option2>',
    async handler(sock, message, args, context) {
      const { chatId } = context;
      const text = args.join(' ');
      const options = text.split(/\bor\b/i).map(o => o.trim()).filter(Boolean);
      if (options.length < 2) {
        return sock.sendMessage(chatId, { text: '🎯 Usage: `.choose <option1> or <option2>`\n\nExample: `.choose pizza or burger`' }, { quoted: message });
      }
      const chosen = r(options);
      await sock.sendMessage(chatId, {
        text: `🎯 *Decision Made!*\n\nOptions:\n${options.map((o, i) => `${i+1}. ${o}`).join('\n')}\n\n🏆 My choice: *${chosen}*\n\n_The bot has spoken!_ 🤖`
      }, { quoted: message });
    }
  },
  {
    command: 'excuse',
    aliases: ['myexcuse', 'excuseme'],
    category: 'fun',
    description: 'Generate a funny excuse',
    usage: '.excuse',
    async handler(sock, message, args, context) {
      const { chatId } = context;
      const excuse = r(EXCUSE_LIST);
      await sock.sendMessage(chatId, {
        text: `🤥 *Your Excuse*\n\n"${excuse}"\n\n_Use at your own risk_ 😂`
      }, { quoted: message });
    }
  },
  {
    command: 'nerd',
    aliases: ['nerdify', 'geekout'],
    category: 'fun',
    description: 'Convert text to nerd speak',
    usage: '.nerd <text>',
    async handler(sock, message, args, context) {
      const { chatId } = context;
      const text = args.join(' ');
      if (!text) return sock.sendMessage(chatId, { text: '🤓 Usage: `.nerd <text>`' }, { quoted: message });
      const map = { a:'α', e:'ε', i:'ι', o:'ο', u:'υ', A:'Α', E:'Ε', I:'Ι', O:'Ο', U:'Υ' };
      const result = text.split('').map(c => map[c] || c).join('');
      const scienceTerms = ['Actually,', 'Technically,', 'According to studies,', 'In theory,', 'Scientifically speaking,'];
      await sock.sendMessage(chatId, {
        text: `🤓 *Nerd Mode*\n\n${r(scienceTerms)} "${result}"\n\n_*adjusts glasses*_ 🤓`
      }, { quoted: message });
    }
  },
  {
    command: 'rate',
    aliases: ['rateme', 'rating'],
    category: 'fun',
    description: 'Rate someone or something out of 10',
    usage: '.rate <name or thing>',
    async handler(sock, message, args, context) {
      const { chatId } = context;
      const subject = args.join(' ').trim() || 'you';
      let rating = 0;
      for (const c of subject.toLowerCase()) rating += c.charCodeAt(0);
      rating = (rating % 11);
      if (subject.toLowerCase().includes('edward md')) rating = 10;
      const emojis = ['😭','😢','😐','🙂','😊','😄','🥰','🤩','💯','🔥','👑'];
      const comments = [
        [0, '...no comment. 💀'],
        [2, 'That\'s rough. Room to grow!'],
        [4, 'Meh, could be worse.'],
        [6, 'Not bad! Pretty decent actually.'],
        [8, 'Really solid! Great stuff!'],
        [9, 'Almost perfect! Exceptional!'],
        [10, 'PERFECT! Top tier! 🏆']
      ];
      const comment = comments.reduce((acc, [min, msg]) => rating >= min ? msg : acc, comments[0][1]);
      await sock.sendMessage(chatId, {
        text: `⭐ *Rating: ${subject}*\n\n${emojis[rating]} *${rating}/10*\n\n${comment}\n\n_Rated by EDWARD MD Bot_`
      }, { quoted: message });
    }
  },
  {
    command: 'iq-test',
    aliases: ['iqtest', 'myiq'],
    category: 'fun',
    description: 'Test your (fake) IQ',
    usage: '.iq-test',
    async handler(sock, message, args, context) {
      const { chatId, senderId } = context;
      let iq = 0;
      for (const c of senderId) iq += c.charCodeAt(0);
      iq = 70 + (iq % 81); // 70-150 range
      const category = iq < 90 ? 'low' : iq < 120 ? 'mid' : 'high';
      const comment = r(IQ_COMMENTS[category]);
      const bar = Math.round((iq - 70) / 8);
      const iqBar = '🟩'.repeat(Math.min(bar, 10)) + '⬜'.repeat(Math.max(0, 10 - bar));
      await sock.sendMessage(chatId, {
        text: `🧠 *IQ Test Result*\n\n${iqBar}\n\n📊 Your IQ: *${iq}*\n\n💬 ${comment}\n\n_Results may vary. For entertainment only!_ 😂`
      }, { quoted: message });
    }
  },
  {
    command: 'lovecalc',
    aliases: ['lovemeter', 'lovelevel', 'love-calc'],
    category: 'fun',
    description: 'Calculate love between two people',
    usage: '.lovecalc <name1> + <name2>',
    async handler(sock, message, args, context) {
      const { chatId } = context;
      const text = args.join(' ');
      const parts = text.split(/[+&]/);
      if (parts.length < 2) {
        return sock.sendMessage(chatId, { text: '💕 Usage: `.lovecalc <name1> + <name2>`\n\nExample: `.lovecalc Romeo + Juliet`' }, { quoted: message });
      }
      const n1 = parts[0].trim();
      const n2 = parts[1].trim();
      let score = 0;
      for (const c of (n1 + n2).toLowerCase()) score += c.charCodeAt(0);
      score = (score % 51) + 50; // 50-100
      const heart = score >= 90 ? '💖' : score >= 75 ? '❤️' : score >= 60 ? '🧡' : '💛';
      const msg = score >= 90 ? 'Destined to be together! 💍' :
                  score >= 75 ? 'Strong love connection! 💕' :
                  score >= 60 ? 'Good potential! Worth a try 😊' :
                  'Friendship first, love later! 🤝';
      await sock.sendMessage(chatId, {
        text: `${heart} *Love Calculator*\n\n${n1} ❤️ ${n2}\n\n💯 Love Score: *${score}%*\n\n${msg}\n\n_For fun only! Real love can't be calculated_ 😄`
      }, { quoted: message });
    }
  },
  {
    command: 'eightpool',
    aliases: ['8pool', 'billiards', 'poolshot'],
    category: 'fun',
    description: 'Play 8-ball pool prediction',
    usage: '.eightpool',
    async handler(sock, message, args, context) {
      const { chatId } = context;
      const shots = [
        '🎱 You scratch! Opponent\'s ball.',
        '🎱 Clean shot! Ball goes in the pocket!',
        '🎱 You miss completely. Try again.',
        '🎱 Incredible bank shot! Two balls sink!',
        '🎱 You hit the cue ball off the table. 😬',
        '🎱 Safety play - you hid the cue ball perfectly.',
        '🎱 Combo shot! Three balls sink in sequence!',
        '🎱 You called the wrong pocket... 😅',
        '🎱 PERFECT SHOT! 8-ball goes in — you WIN! 🏆',
        '🎱 You hit the 8-ball early... GAME OVER! 💀'
      ];
      await sock.sendMessage(chatId, {
        text: `🎱 *8-Ball Pool*\n\nYou step up to the table...\n\n${r(shots)}\n\n_Play again with .eightpool_`
      }, { quoted: message });
    }
  }
];
